# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:3000/api/auth/login

{
username: "fff",
password: "rere",
}

###
POST http://localhost:3000/api/kin/whitelist
Content-Type: application/json

{ "network_id":"Kin Testnet ; December 2018","envelope":"AAAAAA13bjf+QKSXsEMzaHFhtWGxiEoly6Us+ftZxnw2w1RTAAAAZAArLdMAAAABAAAAAAAAAAEAAAAHMS1qcE5nLQAAAAABAAAAAQAAAAANd243\/kCkl7BDM2hxYbVhsYhKJculLPn7WcZ8NsNUUwAAAAEAAAAARnxmy0t1EOaKddzYAHvetWiCPKXHlg9qYPJC\/dWESa0AAAAAAAAAAAABhqAAAAAAAAAAATbDVFMAAABA1Aqqe3eJObd5Mm+RWqvWHMXR3mo51sQnrUEuGSjco\/dgAdp1eMdBCOoA8\/5FKIaPAncT8r4dwj04BY70cVDiCg=="}

###
